source 'https://rubygems.org'

gem 'rails', '>= 5.0.0.beta3', '< 5.1'

gem 'coffee-rails', '~> 4.1.0'
gem 'devise', github: 'plataformatec/devise'
gem 'formtastic'
gem 'haml'
gem 'jquery-rails'
gem 'puma'
gem 'sass-rails', '~> 5.0'
gem 'therubyracer', platforms: :ruby
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'quiet_assets'
  gem 'web-console', '~> 3.0'
end

group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
end

group :production do
  gem 'exception_notification'
  gem 'mysql2'
end
