source 'https://rubygems.org'

gem 'rails', '4.2.5'

gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'formtastic'
gem 'haml'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'therubyracer', platforms: :ruby
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'sqlite3'
end

group :production do
  gem 'exception_notification'
  gem 'mysql2'
end
